# Generated by Django 3.0.7 on 2020-06-05 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_activity',
            name='AP',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='usersapp.User'),
            preserve_default=False,
        ),
    ]
