# Generated by Django 3.0.7 on 2020-06-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_activity_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_periods',
            name='users',
            field=models.ManyToManyField(to='usersapp.User_Activity'),
        ),
    ]
