# Generated by Django 3.0.7 on 2020-06-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_auto_20200605_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_activity',
            old_name='AP',
            new_name='Members',
        ),
    ]
