# Generated by Django 3.0.7 on 2020-06-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_auto_20200605_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_activity',
            name='Members',
        ),
        migrations.AddField(
            model_name='user',
            name='Members',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='usersapp.User_Activity'),
            preserve_default=False,
        ),
    ]
